channels:
    - conda-forge
dependencies:
    - pip >= 21.3.1
    - python=3.10
    - sphinx >= 7.2.2
    - sphinx-autodoc-typehints
    - sphinx-favicon
    - sphinx-rtd-theme
    - pip:
        - sphinx-mathjax-offline
