channels:
    - conda-forge
dependencies:
    - pip >= 21.3.1
    - python=3.10
    - pip:
        - pypoman
        - sphinx >= 7.2.2
        - sphinx-autodoc-typehints
        - sphinx-mathjax-offline
